# Generated by Django 5.0.4 on 2024-05-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='code_ev',
            new_name='code_rap',
        ),
    ]
