# Generated by Django 5.0.4 on 2024-05-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_membre', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(blank=True, max_length=255, null=True)),
                ('cin', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=12)),
                ('photo_profil', models.ImageField(upload_to='images/')),
                ('titre', models.CharField(max_length=25)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('compte', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
