# Generated by Django 5.0.4 on 2024-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ev', models.CharField(max_length=25, unique=True)),
                ('titre', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('dure', models.IntegerField()),
            ],
        ),
    ]
