# Generated by Django 5.0.4 on 2024-05-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activite', '0001_initial'),
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evenement.evenement'),
        ),
    ]
