# Generated by Django 5.0.4 on 2024-05-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='code_ev',
            new_name='code_act',
        ),
    ]
