# Generated by Django 5.0.4 on 2024-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reg', models.CharField(max_length=25)),
                ('nom_reg', models.CharField(max_length=25)),
            ],
        ),
    ]
